dataset: HAR_AAL
output_dir: .
save_model: false
save_res: false
use_bnn: false
x_dim: 561
z_dim: 20
batch_size: 16
epochs: 200
epochs_per_eval: 5
lr: 0.002
lr_theta: 0.001
lr_phi: 0.001
lr_z: 0.002
lr_x: 0.002
alpha: 0.0
beta: 0.1
gamma: 0.0
kl_weight: 0.00005
n_inner_steps: 10
g_d_freq: 1
seed: 123
g_units: [256, 256, 256, 256, 256]
e_units: [256, 256, 256, 256, 256]
dz_units: [256, 128, 64]
dx_units: [256, 128, 64]
missingness_units: [64, 64]
egm_init:
  enabled: true
  n_iter: 5000
  batches_per_eval: 500
posterior:
  test_epochs: 30
  clip_grad_norm: 25.0
